from scipy.stats import gaussian_kde,skew
import matplotlib.pyplot as plt
import numpy as np
a = np.array([2,3,4,5,6,7,8,25])
b = np.array([1,15,16,17,18,19,20,21,22])
c = np.array([10,12,14,15,15,15,16,18,20])
s_a = skew(a)
s_b = skew(b)
s_c = skew(c)
print(s_a)
print(s_b)
print(s_c)
g_a = gaussian_kde(a)
g_b = gaussian_kde(b)
g_c = gaussian_kde(c)
plt.figure(figsize = (9,6))
xa_range = np.linspace(min(a)-2,max(a)+2,500)
ya_range = g_a(xa_range)
bx_range = np.linspace(min(a)-2,max(a)+2,500)
by_range = g_b(bx_range)
xc_range = np.linspace(min(a)-2,max(a)+2,500)
yc_range = g_c(xc_range)
plt.plot(xa_range,ya_range,color ="pink")
plt.plot(bx_range,by_range,color ="skyblue")
plt.plot(xc_range,yc_range,color ="yellow")
plt.show()