#assignment 19 skewness
from scipy.stats import gaussian_kde, skew
import matplotlib.pyplot as plt
import numpy as np
a = np.array([2, 3, 3, 4, 5, 6, 7, 8, 25])
b = np.array([1, 15, 16, 17, 18, 19, 20, 21, 22])
c = np.array([10, 12, 14, 15, 15, 15, 16, 18, 20])
s_a = skew(a)
s_b = skew(b)
s_c = skew(c)
print("Skewness of A:", s_a)
print("Skewness of B:", s_b)
print("Skewness of C:", s_c)
g_a = gaussian_kde(a)
g_b = gaussian_kde(b)
g_c = gaussian_kde(c)
plt.figure(figsize=(9,6))
xa = np.linspace(min(a)-2, max(a)+2, 500)
ya = g_a(xa)
xb = np.linspace(min(b)-2, max(b)+2, 500)
yb = g_b(xb)
xc = np.linspace(min(c)-2, max(c)+2, 500)
yc = g_c(xc)
plt.plot(xa, ya, color="red", label="A (Positive Skew)")
plt.plot(xb, yb, color="blue", label="B (Negative Skew)")
plt.plot(xc, yc, color="yellow", label="C (Approximately Symmetric)")
plt.xlabel("X Value")
plt.ylabel("Density")
plt.title("Skewness")
plt.legend(loc="best")
plt.grid(True)
plt.show()